package display;
import model.*;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.awt.Component;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import java.util.Calendar;
import javax.swing.JFileChooser;
import model.Main;
/**
 *
 * @author Jeffrey Creighton
 */
public class GUI extends javax.swing.JFrame {
    Calendar cal;
    DefaultTableModel available_model;
    DefaultTableModel implemented_model;
    
    Patient_Info_Window patient_info_window;
    
    HashMap<String, Gene> test_map;
    Iterator it;
    String [] implemented_genes;
    
    
    String available_gene;
    String implemented_gene;
    
    String selected_gene;
    boolean focus_available;
    
    String type;
    String urgency;
    
    //Patient Info
    private static String patient_first_name = "";
    private static String patient_last_name = "";
    private static String initial = "";
    private static String patient_address = "";
    private static String patient_city = "";
    private static String patient_state = "";
    private static String patient_dob = "";
    private static String patient_gender = "";
    
    private static String[] available_genes;
    
    private static String output_filepath = "";
    
    /**
     * Creates new form GUI
     */
    
    /**
     * Refreshes the two tables.
     * Perform when a gene type is changed, or when data is imported.
     */
    public void refreshData()
    {
    	for(int i = available_model.getRowCount()-1; i >= 0; i--)
    	{
    		available_model.removeRow(i);
    	}
    	for(int i = implemented_model.getRowCount()-1; i >= 0; i--)
    	{
    		implemented_model.removeRow(i);
    	}
    	test_map = (HashMap) Main.getData();
        Set<String> string_list = test_map.keySet();
        available_genes = new String[string_list.size()];
        //available_model = new DefaultTableModel(0, 1);
        for(String key: string_list){
            String[] temp = {key, test_map.get(key).getType(), test_map.get(key).getUrgency()};
            String[] temp2 = {key, test_map.get(key).getType(), test_map.get(key).getUrgency()};
            available_model.insertRow(available_model.getRowCount(), temp);
            implemented_model.insertRow(implemented_model.getRowCount(), temp2);
        }
    }
    public GUI() {
        /*type = "Homozygous";  
        test_map = new HashMap<String, Gene>();
        test_map.put("Gene 1", new Gene("Gene 1", "wild", "red"));
        test_map.put("Gene 2", new Gene("Gene 2", "wild", "red"));
        test_map.put("Gene 3", new Gene("Gene 3", "wild", "red"));
        test_map.put("Gene 4", new Gene("Gene 4", "wild", "red"));
        test_map.put("Gene 5", new Gene("Gene 5", "wild", "red"));
        
        Main.storeData(test_map);*/
        String[] cols = {"Genes", "Types", "Color"};
        available_model = new DefaultTableModel(cols, 0);
        String[] cols2 = {"Genes", "Types", "Color"};
        implemented_model = new DefaultTableModel(cols2, 0); 
        refreshData();
       
        initComponents(); 
        
    }
    
    public void displayException(Exception e){
        JFrame frame = new JFrame("Error");
    	JOptionPane.showMessageDialog(frame , e.getMessage());
    }
    
    private boolean check_implemented_list(Object o) {
        boolean already_here = false;
        Object item; //place holder for checking contents of existing rows 
        for (int i = 0; i < implemented_model.getRowCount(); i++) {
            item = String.valueOf(implemented_model.getValueAt(i, 0));
            if (item.equals(available_gene)) {
                already_here = true;
            }
        }
        return already_here;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        primary_panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        implemented_gene_table = new javax.swing.JTable();
        include_gene_button = new javax.swing.JButton();
        exclude_gene_button = new javax.swing.JButton();
        generate_report_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        selected_text = new javax.swing.JTextField();
        edit_type_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        preview_detail_button = new javax.swing.JButton();
        save_as_button = new javax.swing.JButton();
        patient_info_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        available_gene_table = new javax.swing.JTable();
        remove_button = new javax.swing.JButton();
        add_button = new javax.swing.JButton();
        urgency_box = new javax.swing.JComboBox();
        type_box = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        import_button = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Genomic Solutions Now!");

        primary_panel.setBackground(new java.awt.Color(102, 153, 255));
        primary_panel.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        implemented_gene_table.setModel(implemented_model);
        implemented_gene_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        implemented_gene_table.setSelectionBackground(new java.awt.Color(102, 255, 204));
        implemented_gene_table.setSelectionForeground(new java.awt.Color(0, 0, 0));
        implemented_gene_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                implemented_gene_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(implemented_gene_table);

        include_gene_button.setText("Include");
        include_gene_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                include_gene_buttonMouseClicked(evt);
            }
        });

        exclude_gene_button.setText("Exclude");
        exclude_gene_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exclude_gene_buttonMouseClicked(evt);
            }
        });

        generate_report_button.setText("Generate Report");
        generate_report_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_report_buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Available Genes");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Implemented Genes");

        selected_text.setEditable(false);
        selected_text.setBackground(new java.awt.Color(255, 102, 0));

        edit_type_button.setText("Edit Type");
        edit_type_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_type_buttonMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Report Generation");

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        preview_detail_button.setText("Preview Details");
        preview_detail_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                preview_detail_buttonMouseClicked(evt);
            }
        });

        save_as_button.setText("Save As");
        save_as_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save_as_buttonMouseClicked(evt);
            }
        });

        patient_info_button.setText("Edit Patient Info");
        patient_info_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patient_info_buttonMouseClicked(evt);
            }
        });

        available_gene_table.setModel(available_model);
        available_gene_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        available_gene_table.setSelectionBackground(new java.awt.Color(255, 102, 0));
        available_gene_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                available_gene_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(available_gene_table);
        if (available_gene_table.getColumnModel().getColumnCount() > 0) {
            available_gene_table.getColumnModel().getColumn(0).setResizable(false);
            available_gene_table.getColumnModel().getColumn(0).setHeaderValue("Available Genes");
        }

        remove_button.setText("Remove");

        add_button.setText("Add");

        urgency_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "red", "yellow", "green", "blue" }));

        type_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Absent ", "Present", "Homozygous", "Heterozygous", "Wild" }));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Type");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Urgency");

        import_button.setText("Import");

        javax.swing.GroupLayout primary_panelLayout = new javax.swing.GroupLayout(primary_panel);
        primary_panel.setLayout(primary_panelLayout);
        primary_panelLayout.setHorizontalGroup(
            primary_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(primary_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(primary_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(primary_panelLayout.createSequentialGroup()
                        .addGroup(primary_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(primary_panelLayout.createSequentialGroup()
                                .addComponent(add_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(remove_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(primary_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exclude_gene_button, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(include_gene_button, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(primary_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(primary_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(primary_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(primary_panelLayout.createSequentialGroup()
                                    .addComponent(edit_type_button, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(selected_text))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, primary_panelLayout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(type_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(urgency_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(primary_panelLayout.createSequentialGroup()
                        .addComponent(import_button)
                        .addGap(18, 18, 18)
                        .addComponent(patient_info_button, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(save_as_button, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(preview_detail_button, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generate_report_button, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(primary_panelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        primary_panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {add_button, edit_type_button, remove_button});

        primary_panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {generate_report_button, import_button, patient_info_button, preview_detail_button, save_as_button});

        primary_panelLayout.setVerticalGroup(
            primary_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primary_panelLayout.createSequentialGroup()
                .addGroup(primary_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(primary_panelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, primary_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addGap(11, 11, 11)
                .addGroup(primary_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(primary_panelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(primary_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selected_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(primary_panelLayout.createSequentialGroup()
                                .addComponent(edit_type_button)
                                .addGap(18, 18, 18)
                                .addGroup(primary_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(type_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(urgency_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(primary_panelLayout.createSequentialGroup()
                        .addGroup(primary_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(primary_panelLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(include_gene_button)
                                .addGap(37, 37, 37)
                                .addComponent(exclude_gene_button))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(primary_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_button)
                            .addComponent(remove_button))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(primary_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patient_info_button)
                    .addComponent(save_as_button)
                    .addComponent(preview_detail_button)
                    .addComponent(generate_report_button)
                    .addComponent(import_button))
                .addGap(18, 18, 18))
        );

        primary_panelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {generate_report_button, import_button, patient_info_button, preview_detail_button, save_as_button});

        jMenu2.setText("Edit");

        jMenu1.setText("Edit Defaults");

        jMenuItem3.setText("Disease");
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("Gene");
        jMenu1.add(jMenuItem1);

        jMenu4.setText("Language");

        jMenuItem2.setText("English");
        jMenu4.add(jMenuItem2);

        jMenuItem4.setText("Spanish");
        jMenu4.add(jMenuItem4);

        jMenuItem6.setText("Add New");
        jMenu4.add(jMenuItem6);

        jMenu1.add(jMenu4);

        jMenu2.add(jMenu1);

        jMenuItem5.setText("Change Language");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(primary_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(primary_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patient_info_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patient_info_buttonMouseClicked
        Patient_Info_Window patientw = new Patient_Info_Window();
        patientw.setVisible(true);
    }//GEN-LAST:event_patient_info_buttonMouseClicked

    private void save_as_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_as_buttonMouseClicked
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            set_output_file(chooser.getSelectedFile().toString());
        }
    }//GEN-LAST:event_save_as_buttonMouseClicked

    private void preview_detail_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preview_detail_buttonMouseClicked
        cal = Calendar.getInstance();
        int y = cal.get(Calendar.YEAR);
        int m = cal.get(Calendar.MONTH);
        int d = cal.get(Calendar.DAY_OF_MONTH);
        String id = get_last_name() + get_first_name().substring(0, 1) +"-"+ y + "/" + m + "/" + d;
        PreviewWindow pw = new PreviewWindow(this, true, implemented_model, get_first_name(), get_last_name(), get_initial(), get_address(), get_city(), get_state(), get_dob(), get_gender(), id);
        pw.setVisible(true);
    }//GEN-LAST:event_preview_detail_buttonMouseClicked

    private void edit_type_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_type_buttonMouseClicked
        for(int i=0; i<implemented_model.getRowCount(); i++){
            Object item = String.valueOf(implemented_model.getValueAt(i, 0));
                Gene old = Main.getGene(selected_gene.toString());
                Gene new_gene = new Gene(selected_gene.toString(), type_box.getSelectedItem().toString(), urgency_box.getSelectedItem().toString(), old.getRSNumber(), old.getVariant());
                Main.setGene(new_gene);
                refreshData();
        }
    }//GEN-LAST:event_edit_type_buttonMouseClicked

    private void generate_report_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_report_buttonActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_generate_report_buttonActionPerformed

    private void exclude_gene_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exclude_gene_buttonMouseClicked
            for(int i=0; i<implemented_model.getRowCount(); i++){
                String item = String.valueOf(implemented_model.getValueAt(i, 0));
                if(selected_gene.equals(item)){
                    Main.deselectGene(item.toString());
                    implemented_model.removeRow(i);
                    Main.getSelected();
                    Main.getData();
                }
            }
    }//GEN-LAST:event_exclude_gene_buttonMouseClicked

    private void include_gene_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_include_gene_buttonMouseClicked
            if (selected_gene != null) { //make sure that a gene was selected
                if (!check_implemented_list(selected_gene)) { //check to see if the gene is already included
                    Object[] to_insert = {selected_gene, type};
                    Main.selectGene(selected_gene.toString());
                    Gene gene = new Gene(selected_gene.toString());
                    //gene.setType(type);
                    Main.setGene(gene);
                    implemented_model.addRow(to_insert);
                    selected_gene = null;
                    Main.getSelected();
                    Main.getData();
                }
            }
    }//GEN-LAST:event_include_gene_buttonMouseClicked

    private void import_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_import_buttonMouseClicked
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            Main.readGene(fc.getSelectedFile().toString());
        }
    }//GEN-LAST:event_import_buttonMouseClicked
    
    private void add_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMouseClicked
        AddGeneWindow aw =  new AddGeneWindow();
        aw.setVisible(true);
        refreshData();
    }//GEN-LAST:event_add_buttonMouseClicked

    private void implemented_gene_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_implemented_gene_tableMouseClicked
        focus_available = false;
        selected_gene = implemented_gene_table.getValueAt(implemented_gene_table.getSelectedRow(), 0).toString();
        selected_text.setText(selected_gene);
    }//GEN-LAST:event_implemented_gene_tableMouseClicked

    private void available_gene_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_available_gene_tableMouseClicked
        focus_available = true;
        selected_gene = available_gene_table.getValueAt(available_gene_table.getSelectedRow(), 0).toString();
        selected_text.setText(selected_gene);
    }//GEN-LAST:event_available_gene_tableMouseClicked
 
    
    
    
    public static void set_first_name(String n){
        patient_first_name = n;
    }
    public static String get_first_name(){
        return patient_first_name;
    }
    public static void set_last_name(String l){
        patient_last_name = l;
    }
    public static String get_last_name(){
        return patient_last_name;
    }
    public static void set_initial(String i){
        initial = i;
    }
    public static String get_initial(){
        return initial;
    }
    public static void set_address(String addr){
        patient_address = addr;
    }
    public static String get_address(){
        return patient_address;
    }
    public static void set_city(String c){
        patient_city = c;
    }
    public static String get_city(){
        return patient_city;
    }
    public static void set_state(String s){
        patient_state = s;
    }
    public static String get_state(){
        return patient_state;
    }
    public static void set_dob(String d){
        patient_dob = d;
    }
    public static String get_dob(){
        return patient_dob;
    }
    public static void set_gender(String g){
        patient_gender = g;
    }
    public static String get_gender(){
        return patient_gender;
    }   
    public static void set_output_file(String f) {
     output_filepath = f;   
    }
    public static String get_output_file() {
        return output_filepath;
    }
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        // Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        // If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         // For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         //
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Create and display the form //
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
			public void run() {
                new GUI().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JTable available_gene_table;
    private javax.swing.JButton edit_type_button;
    private javax.swing.JButton exclude_gene_button;
    private javax.swing.JButton generate_report_button;
    private javax.swing.JTable implemented_gene_table;
    private javax.swing.JButton import_button;
    private javax.swing.JButton include_gene_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton patient_info_button;
    private javax.swing.JButton preview_detail_button;
    private javax.swing.JPanel primary_panel;
    private javax.swing.JButton remove_button;
    private javax.swing.JButton save_as_button;
    private javax.swing.JTextField selected_text;
    private javax.swing.JComboBox type_box;
    private javax.swing.JComboBox urgency_box;
    // End of variables declaration//GEN-END:variables
}
