package display;

import model.Patient;

/**
 *
 * @author Jeffrey Creighton
 */
public class Patient_Info_Window extends javax.swing.JFrame {
    Patient patient;
    /**
     * Creates new form Patient_Info_Window
     */
    public Patient_Info_Window(Patient patient) {
        this.patient = patient;
        initComponents();
        
        first_name_text.setText(patient.get_first_name());
        last_name_text.setText(patient.get_last_name());
        initial_text.setText(patient.get_initial());
        addr_text.setText(patient.get_address());
        city_text.setText(patient.get_city());
        state_text.setText(patient.get_state());
        month_box.setSelectedIndex(patient.get_month()-1);
        day_box.setSelectedIndex(patient.get_day()-1);
        year_text.setText(patient.get_year());
        if(patient.get_gender().equals("M")){
            gender_box.setSelectedIndex(0);
        } else if(patient.get_gender().equals("F")) {
            gender_box.setSelectedIndex(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        info_label = new javax.swing.JPanel();
        name_label = new javax.swing.JLabel();
        last_name_text = new javax.swing.JTextField();
        addr_label = new javax.swing.JLabel();
        city_label = new javax.swing.JLabel();
        city_text = new javax.swing.JTextField();
        state_label = new javax.swing.JLabel();
        state_text = new javax.swing.JTextField();
        dob_label = new javax.swing.JLabel();
        year_text = new javax.swing.JTextField();
        gender_label = new javax.swing.JLabel();
        save_info_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        first_name_text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        initial_text = new javax.swing.JTextField();
        addr_text = new javax.swing.JTextField();
        gender_box = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        month_box = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        day_box = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        info_label.setBackground(new java.awt.Color(204, 204, 204));

        name_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name_label.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        name_label.setText("Last Name:");

        addr_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addr_label.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        addr_label.setText("Address:");

        city_label.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        city_label.setText("City:");

        state_label.setText("State:");

        dob_label.setText("Date of Birth:");

        gender_label.setText("Gender:");

        save_info_button.setText("Save");
        save_info_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save_info_buttonMouseClicked(evt);
            }
        });

        jLabel1.setText("First Name:");

        jLabel2.setText("Middle Initial:");

        gender_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));

        jLabel3.setText("Month:");

        month_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jLabel4.setText("Day:");

        day_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel5.setText("Year:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("(yyyy)");

        javax.swing.GroupLayout info_labelLayout = new javax.swing.GroupLayout(info_label);
        info_label.setLayout(info_labelLayout);
        info_labelLayout.setHorizontalGroup(
            info_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_labelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(info_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dob_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(city_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addr_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(info_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(info_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(info_labelLayout.createSequentialGroup()
                            .addComponent(last_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(first_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(initial_text, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(addr_text)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info_labelLayout.createSequentialGroup()
                            .addComponent(city_text, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(state_label, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(state_text, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(gender_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(gender_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 95, Short.MAX_VALUE)))
                    .addGroup(info_labelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(month_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(day_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGroup(info_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info_labelLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(save_info_button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(info_labelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(info_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(year_text, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        info_labelLayout.setVerticalGroup(
            info_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_labelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(info_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(info_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(last_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(first_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(initial_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(info_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addr_label)
                    .addComponent(addr_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(info_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(city_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city_label)
                    .addComponent(state_label)
                    .addComponent(state_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender_label)
                    .addComponent(gender_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(info_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(info_labelLayout.createSequentialGroup()
                        .addGroup(info_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dob_label)
                            .addComponent(jLabel3)
                            .addComponent(month_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(day_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6)
                        .addGap(3, 3, 3)
                        .addComponent(save_info_button))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        info_labelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addr_label, addr_text, city_label, city_text, day_box, dob_label, first_name_text, gender_box, gender_label, initial_text, jLabel1, jLabel2, jLabel3, jLabel5, last_name_text, month_box, name_label, save_info_button, state_label, state_text, year_text});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(info_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(info_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_info_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_info_buttonMouseClicked
        patient.set_first_name(first_name_text.getText().toString().trim());
        patient.set_last_name(last_name_text.getText().toString().trim());
        patient.set_initial(initial_text.getText().toString().trim());
        patient.set_address(addr_text.getText().toString().trim());
        patient.set_city(city_text.getText().toString().trim());
        patient.set_state(state_text.getText().toString().trim());
        patient.set_month(Integer.parseInt(month_box.getSelectedItem().toString().trim()));
        patient.set_day(Integer.parseInt(day_box.getSelectedItem().toString().trim()));
        patient.set_year(year_text.getText().toString().trim());
        patient.set_gender(gender_box.getSelectedItem().toString().trim());    
        this.setVisible(false);
    }//GEN-LAST:event_save_info_buttonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addr_label;
    private javax.swing.JTextField addr_text;
    private javax.swing.JLabel city_label;
    private javax.swing.JTextField city_text;
    private javax.swing.JComboBox day_box;
    private javax.swing.JLabel dob_label;
    private javax.swing.JTextField first_name_text;
    private javax.swing.JComboBox gender_box;
    private javax.swing.JLabel gender_label;
    private javax.swing.JPanel info_label;
    private javax.swing.JTextField initial_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField last_name_text;
    private javax.swing.JComboBox month_box;
    private javax.swing.JLabel name_label;
    private javax.swing.JButton save_info_button;
    private javax.swing.JLabel state_label;
    private javax.swing.JTextField state_text;
    private javax.swing.JTextField year_text;
    // End of variables declaration//GEN-END:variables
}
